package com.queuemed.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;
import com.queuemed.R;
import com.queuemed.models.Appointment;
import com.queuemed.utils.SharedPrefManager;

public class BookAppointmentFragment extends Fragment {

    private EditText etDate, etTime;
    private Button btnBook;
    private DatabaseReference dbRef;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment_book_appointment, container, false);

        etDate = view.findViewById(R.id.etDate);
        etTime = view.findViewById(R.id.etTime);
        btnBook = view.findViewById(R.id.btnBook);

        // Get Firebase reference for current patient
        SharedPrefManager sp = new SharedPrefManager(getContext());
        String userEmailKey = sp.getUserEmail().replace(".", "_"); // Firebase keys can't have dots
        dbRef = FirebaseDatabase.getInstance().getReference("appointments").child(userEmailKey);

        btnBook.setOnClickListener(v -> {
            String date = etDate.getText().toString().trim();
            String time = etTime.getText().toString().trim();

            if(date.isEmpty() || time.isEmpty()){
                Toast.makeText(getContext(), "Please enter date and time", Toast.LENGTH_SHORT).show();
                return;
            }

            String patientName = sp.getUserName();
            String patientEmail = sp.getUserEmail();

            // Status is always Pending when booking
            Appointment appointment = new Appointment(
                    null,              // ID will be generated by Firebase push()
                    patientName,
                    patientEmail,
                    date,
                    time,
                    "Pending"
            );

            bookAppointment(appointment);
        });


        return view;
    }

    private void bookAppointment(Appointment newAppointment) {
        dbRef.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                boolean conflict = false;
                for (DataSnapshot ds : snapshot.getChildren()) {
                    Appointment existing = ds.getValue(Appointment.class);
                    if (existing != null &&
                            existing.getDate().equals(newAppointment.getDate()) &&
                            existing.getTime().equals(newAppointment.getTime())) {
                        conflict = true;
                        break;
                    }
                }

                if(conflict){
                    Toast.makeText(getContext(),
                            "You already have an appointment at this time!", Toast.LENGTH_SHORT).show();
                } else {
                    dbRef.child(newAppointment.getId()).setValue(newAppointment)
                            .addOnSuccessListener(aVoid -> Toast.makeText(getContext(),
                                    "Appointment booked successfully!", Toast.LENGTH_SHORT).show())
                            .addOnFailureListener(e -> Toast.makeText(getContext(),
                                    "Failed to book appointment: " + e.getMessage(), Toast.LENGTH_SHORT).show());
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError error) {
                Toast.makeText(getContext(),
                        "Failed to check existing appointments", Toast.LENGTH_SHORT).show();
            }
        });
    }
}
